### PR TITLE
Changes http_poison to 0.9 dependencies

### PR DESCRIPTION
**Pull request by ngdelcastillo**

### CODE REVIEW

**Comment by ngdelcastillo** [comment]
hmm...weird..I'm getting all 51 tests passing in my local ```
Finished in 16.8 seconds
51 tests, 0 failures
```

**Comment by mkrogemann** [comment]
Looks like an issue with mix on older versions of Elixir.
Does this currently block you? Do you depend on version 0.9.x of httpoison? 
In fact, I just saw that there's already a 0.10.0 out. 
Looks like I will have to run some tests with updated dependencies and maybe stop supporting older Elixir versions (travis fails for 1.0 and 1.1).

**Comment by locolupo** [comment]
@ngdelcastillo @mkrogemann i am already investigating, https://travis-ci.org/locolupo/couchdb_connector/builds/174290493

it seems that we have to drop a really old elixir version in travis in favor of fresh dependencies.

**Comment by mkrogemann** [comment]
But why do we have to update httpoison? I would like to understand if this is a blocker and if so, then 0.9 would again be a blocker for other users.

**Comment by mkrogemann** [comment]
I am in the process of finalizing a 0.4 release which will allow users of the connector to apply a wide range of httpoison versions (0.8.x, 0.9.x, 0.10.x). ETA next weekend

**Comment by mkrogemann** [comment]
@ngdelcastillo Please have a look at release 0.4. It would allow you to use version 0.9 of httpoison (or even 0.10)

**Pull request closed without merging**
